name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - '!README.md'
      - '!docker-compose.yml'
  pull_request:
    branches: [ main ]

jobs:

  build2022:
    name: "Build Server 2022"
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: .\Build.ps1 -LTSC 2022
    
    - name: Docker Login
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Publish the Docker image
      if: github.ref == 'refs/heads/main'
      run: docker push dechertnicholas/space-engineers-ds-windows:ltsc2022

  build2019:
    name: "Build Server 2019"
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: .\Build.ps1 -LTSC 2019
    
    - name: Docker Login
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Publish the Docker image
      if: github.ref == 'refs/heads/main'
      run: docker push dechertnicholas/space-engineers-ds-windows:ltsc2019