name: Docker Image CI

on:
  push:
    branches: [ main ]
    path:
      - '!README.md'
      - '!docker-compose.yml'
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: docker build . -t dechertnicholas/space-engineers-ds-windows:latest
      
    - name: Docker Login
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Publish the Docker image
      run: docker push dechertnicholas/space-engineers-ds-windows:latest
