name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t dechertnicholas/space-engineers-ds-windows:latest
    - name: Docker Login
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.10.0
      with:
        context: .
        tags: dechertnicholas/space-engineers-ds-windows:latest
        push: true
